### ISSUE TITLE
Mass Link 1 Quality

### ISSUE THREAD

**Issue by ariopratomo** [anasrar/Samehadaku-Lewatin#1]
Tambahin fitur mass link 1 quality dong bang,
 misal x265 = semua link dari quality x265 langsung ke bypass semua terus disimpen di file .txt gitu 😁

**Comment by anasrar** [comment]
> Tambahin fitur mass link 1 quality dong bang,
> misal x265 = semua link dari quality x265 langsung ke bypass semua terus disimpen di file .txt gitu 😁

maksudnya semua link dengan resolusi yang sama {360p, 480p, etc} atau formatnya {mkv, mp4, ect} ??
kalo terus di simpen di file text pasti bisa

**Comment by ariopratomo** [comment]
Semua link dengan format yang sama bang, di file txtnya ada keterangan resolusinya juga

**Comment by anasrar** [comment]
paling cuma bisa lewatin 1 safelink, terlalu banyak looping kadang ke overwrite
di sini saia pake JSON aja pak, biar mudah lagi pengolahannya

![demo template](https://user-images.githubusercontent.com/38805204/53240498-6b6ed080-36d1-11e9-8129-81a94ac12e7a.gif)

**Comment by anasrar** [comment]
Done
![demo template](https://user-images.githubusercontent.com/38805204/53244570-dc1bea00-36dd-11e9-9b7c-459d3c2c6cbb.gif)
