### ISSUE TITLE
Cannot find module 'babel-register'

### ISSUE THREAD

**Issue by S11720037** [anasrar/Samehadaku-Lewatin#2]
![Screenshot from 2019-05-20 09-47-36](https://user-images.githubusercontent.com/50015208/57991930-5c3acb80-7ae4-11e9-8b2c-a951baf7ee6f.png)

**Comment by anasrar** [comment]
```bash
$ npm install --save-dev babel-preset-env babel-register
```

**Comment by anasrar** [comment]
i will update the readme

**Comment by anasrar** [comment]
i already try
```bash
$ npm i
```
it work, npm automatically install devDependencies

**Comment by S11720037** [comment]
> ![Screenshot from 2019-05-20 09-47-36](https://user-images.githubusercontent.com/50015208/57991930-5c3acb80-7ae4-11e9-8b2c-a951baf7ee6f.png)

tadi ini saya install pake npm install samehadaku......., tidak terinstall sempurna.

setelah install pake git  clone, masalah yang tadi tidak muncul. (tidak perlu menginstall tambahan babel dll), dan bisa terinstall dengan baik

**Comment by S11720037** [comment]
> i will update the readme

btw, di linux saya g bisa npm install dan npm link kalo gada akses root.
tolong tambahkan sudo di wikinya

**Comment by anasrar** [comment]
> > i will update the readme
> 
> btw, di linux saya g bisa npm install dan npm link kalo gada akses root.
> tolong tambahkan sudo di wikinya

https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by anasrar** [comment]
![image](https://user-images.githubusercontent.com/38805204/58221370-838bd580-7d3c-11e9-8077-c54c2eb23f9a.png)
fixed and tested with `npx samehadaku-lewatin list`
